spring:
  application:
    name: cloud-chat
  datasource:
    url: jdbc:mysql:127.0.0.1:3306/chat
    password: root
    username: root
    #druid的配置
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  kafka:
    producer:
      bootstrap-servers: 111.230.47.161:9092
      acks: -1
      client-id: kafka-producer
      batch-size: 5
      retries: 0
      buffer-memory: 40960
server:
  port: 8080
mybatis:
  type-aliases-package: com.demo.demo_web.entity
  mapper-locations: classpath*:mapper/*.xml
#logging:
#  level: info